# CC BY-NC-SA 4.0 - jean-marc "jihem" quere 2026
# Example of using the Firebird client.
# nim c -r demo.nim
# (Environment variables : FB_DB, FB_USER, FB_PASSWORD)

import std/[os, times]
import firebird/fbclient

type Client = object
  id: int
  name: string
  credit: float
  active: bool

proc main() =
  let opts = ConnectOptions(
    database: getEnv("FB_DB", "localhost://tmp/demo.fdb"),
    user: getEnv("FB_USER", "SYSDBA"),
    password: getEnv("FB_PASSWORD", "masterkey"))

  echo "libfbclient : ", clientVersion()

  # Création de la base si elle n'existe pas encore
  let db =
    try: connect(opts)
    except FbError: createDatabase(opts, pageSize = 16384)
  defer: db.close()

  let inf = db.info
  echo "Server : ", inf.serverVersion, " - ODS ", inf.odsVersion, ".",
       inf.odsMinorVersion, " - pages of ", inf.pageSize, " bytes"

  # DDL (auto-commit actif par défaut)
  if "CLIENTS" notin db.tableNames:
    discard db.exec("""
      CREATE TABLE clients (
        id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name    VARCHAR(100) NOT NULL,
        credit  NUMERIC(15,2) DEFAULT 0,
        active  BOOLEAN DEFAULT TRUE,
        addate  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        notes   BLOB SUB_TYPE TEXT,
        photo   BLOB SUB_TYPE BINARY)""")

  # Insertion with parameters of various types, and RETURNING.
  let r = db.getRow("INSERT INTO clients (name, credit, active, notes, photo) " &
                    "VALUES (?, ?, ?, ?, ?) RETURNING id, addate",
                    "Alice", decimal(123456, -2), true, "A rather long note...",
                    @[0x89'u8, 0x50, 0x4E, 0x47])
  echo "New id : ", r.get()["ID"].asInt, " added on ", r.get()["ADDATE"]

 # Prepared statement reused in an explicit transaction.
  db.withTransaction(tx, TransactionOptions(isolation: ilConcurrency, lockTimeout: 5)):
    let ins = tx.prepare("INSERT INTO clients (name, credit, active) VALUES (?, ?, ?)")
    defer: ins.close()
    for i in 1..3:
      discard ins.exec(tx, "Client " & $i, float(i) * 10.5, i mod 2 == 0)
    tx.savepoint("SP1")
    discard tx.exec("DELETE FROM clients WHERE name = ?", "Client 3")
    tx.rollbackToSavepoint("SP1")          # la suppression est annulée
    echo "Transaction n° ", tx.id

  # Streaming...
  for row in db.rows("SELECT id, name, credit, active, notes FROM clients WHERE credit >= ?", 0):
    echo row

  # Reading towards Nim objects.
  for row in db.query("SELECT id, name, credit, active FROM clients ORDER BY id"):
    let c = row.to(Client)
    echo c

  # Scalar values, NULL, and Option.
  echo "Nombre de clients : ", db.getValue("SELECT COUNT(*) FROM clients").asInt
  let v = db.getValue("SELECT notes FROM clients WHERE name = ?", "Client 1")
  echo "Notes of Client 1 : ", v.get(Option[string])

  # Mise à jour et nombre de lignes affectées.
  let n = db.exec("UPDATE clients SET credit = credit * ? WHERE active", 1.1)
  echo n, " row(s) updated"

  # Plan d'exécution et métadonnées.
  let st = db.prepare("SELECT name FROM clients WHERE id = ?")
  echo "Plan : ", st.plan
  echo "Instruction type : ", st.kind
  for c in st.columns:
    echo "  column ", c.alias, " : ", c.sqlTypeName
  st.close()

  # Date/time
  discard db.exec("UPDATE clients SET addate = ? WHERE id = 1", now())
  echo db.getValue("SELECT addate FROM clients WHERE id = 1").asDateTime

  # Error handling
  try:
    discard db.exec("INSERT INTO clients (id, name) VALUES (1, 'duplicate')")
  except FbError as e:
    echo "Expected error: SQLSTATE=", e.sqlState, " SQLCODE=", e.sqlCode
    echo e.messages[0]

main()
